# Generated by Django 5.2.3 on 2025-10-23 18:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("servicos", "0008_regularizacaomei"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo_servico",
                    models.CharField(
                        choices=[
                            ("abrir_mei", "Abrir MEI"),
                            ("regularizar_mei", "Regularizar MEI"),
                            ("declaracao_mei", "Declaração Anual MEI"),
                            ("baixar_mei", "Baixar MEI"),
                        ],
                        max_length=50,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("approved", "Aprovado"),
                            ("rejected", "Rejeitado"),
                            ("cancelled", "Cancelado"),
                            ("in_process", "Em Processamento"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("nome_cliente", models.CharField(max_length=200)),
                ("email_cliente", models.EmailField(max_length=254)),
                ("telefone_cliente", models.CharField(max_length=20)),
                (
                    "mp_payment_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "mp_preference_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mp_external_reference",
                    models.CharField(max_length=100, unique=True),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("dados_extras", models.JSONField(blank=True, default=dict)),
                (
                    "solicitacao_mei",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicos.solicitacaomei",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento",
                "verbose_name_plural": "Pagamentos",
                "ordering": ["-criado_em"],
            },
        ),
    ]
