# Generated by Django 4.2.7 on 2025-10-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Depoimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="depoimentos/"),
                ),
                ("conteudo", models.TextField(max_length=500)),
                ("cargo", models.CharField(blank=True, max_length=100)),
                ("empresa", models.CharField(blank=True, max_length=100)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Depoimento",
                "verbose_name_plural": "Depoimentos",
                "ordering": ["-criado_em"],
            },
        ),
    ]
