# Generated by Django 5.2.3 on 2025-10-15 18:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaPlanoContas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("entrada", "Entrada"), ("saida", "Saída")],
                        max_length=10,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Categoria do Plano de Contas",
                "verbose_name_plural": "Categorias do Plano de Contas",
                "ordering": ["tipo", "nome"],
            },
        ),
        migrations.CreateModel(
            name="SaldoCaixa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(unique=True)),
                (
                    "saldo_inicial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_entradas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_saidas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "saldo_final",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Saldo do Caixa",
                "verbose_name_plural": "Saldos do Caixa",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="SubcategoriaPlanoContas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategorias",
                        to="dashboard.categoriaplanocontas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcategoria do Plano de Contas",
                "verbose_name_plural": "Subcategorias do Plano de Contas",
                "ordering": ["categoria", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos",
                        to="dashboard.subcategoriaplanocontas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto/Serviço",
                "verbose_name_plural": "Produtos/Serviços",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cliente_nome", models.CharField(max_length=200)),
                ("cliente_email", models.EmailField(blank=True, max_length=254)),
                ("cliente_telefone", models.CharField(blank=True, max_length=20)),
                ("cliente_cpf_cnpj", models.CharField(blank=True, max_length=18)),
                ("quantidade", models.PositiveIntegerField(default=1)),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("valor_final", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("pago", "Pago"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dinheiro", "Dinheiro"),
                            ("cartao_credito", "Cartão de Crédito"),
                            ("cartao_debito", "Cartão de Débito"),
                            ("pix", "PIX"),
                            ("transferencia", "Transferência Bancária"),
                            ("boleto", "Boleto"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("data_venda", models.DateTimeField(auto_now_add=True)),
                ("data_pagamento", models.DateTimeField(blank=True, null=True)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendas",
                        to="dashboard.produto",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendas_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Venda",
                "verbose_name_plural": "Vendas",
                "ordering": ["-data_venda"],
            },
        ),
        migrations.CreateModel(
            name="MovimentacaoCaixa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("entrada", "Entrada"), ("saida", "Saída")],
                        max_length=10,
                    ),
                ),
                ("descricao", models.CharField(max_length=200)),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("data_movimentacao", models.DateTimeField()),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentacoes_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subcategoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentacoes",
                        to="dashboard.subcategoriaplanocontas",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentacoes",
                        to="dashboard.venda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentação de Caixa",
                "verbose_name_plural": "Movimentações de Caixa",
                "ordering": ["-data_movimentacao"],
            },
        ),
    ]
