# Generated by Django 5.2.3 on 2025-10-15 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaocaixa",
            name="categoria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimentacoes",
                to="dashboard.categoriaplanocontas",
            ),
        ),
        migrations.AlterField(
            model_name="movimentacaocaixa",
            name="subcategoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimentacoes",
                to="dashboard.subcategoriaplanocontas",
            ),
        ),
    ]
