# Generated by Django 4.2.7 on 2025-10-15 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_movimentacaocaixa_categoria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimentacaocaixa",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimentacoes",
                to="dashboard.categoriaplanocontas",
            ),
        ),
    ]
