# Generated by Django 4.2.7 on 2025-10-14 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-criado_em"],
                "verbose_name": "Post do Blog",
                "verbose_name_plural": "Posts do Blog",
            },
        ),
        migrations.AddField(
            model_name="post",
            name="data_publicacao",
            field=models.DateTimeField(
                blank=True,
                help_text="Data de publicação personalizada. Deixe vazio para usar a data de criação.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Descrição para SEO (máx. 160 caracteres). Se vazio, usará o resumo.",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="nome_autor_display",
            field=models.CharField(
                blank=True,
                help_text="Nome do autor para exibição (se diferente do usuário). Deixe vazio para usar o nome do usuário.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="palavras_chave",
            field=models.CharField(
                blank=True,
                help_text="Palavras-chave separadas por vírgula (ex: MEI, empreendedorismo, contabilidade)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tags_seo",
            field=models.TextField(
                blank=True,
                help_text='\n        Tags HTML adicionais para SEO (opcional). \n        Ex: <meta property="article:section" content="Negócios">\n        ',
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="autor",
            field=models.ForeignKey(
                help_text="Autor do artigo (usuário do sistema)",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="conteudo",
            field=models.TextField(
                help_text="\n        Conteúdo principal do artigo em HTML. \n        Você pode usar tags como: <h2>, <h3>, <p>, <strong>, <em>, <ul>, <ol>, <li>, <a>, <blockquote>\n        Evite usar <h1> pois já é usado pelo título.\n        "
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="imagem",
            field=models.ImageField(
                blank=True,
                help_text="Imagem destacada do artigo (recomendado: 1200x630px)",
                null=True,
                upload_to="blog/",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="publicado",
            field=models.BooleanField(
                default=True, help_text="Marque para tornar o artigo visível no site"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="resumo",
            field=models.TextField(
                help_text="Breve resumo do post usado na listagem e redes sociais (máx. 300 caracteres)",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                help_text="URL amigável do artigo (gerada automaticamente a partir do título)",
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="titulo",
            field=models.CharField(
                help_text="Título principal do artigo (máx. 200 caracteres)",
                max_length=200,
            ),
        ),
    ]
