# Generated by Django 5.2.3 on 2025-10-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_options_post_data_publicacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="destaque_home",
            field=models.BooleanField(
                default=False,
                help_text="Marque para exibir este artigo na página inicial (máximo 3 recomendados)",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="conteudo",
            field=models.TextField(
                help_text="Use o editor para criar conteúdo com formatação rica. Evite títulos H1 (use H2, H3, etc.)"
            ),
        ),
    ]
