# Generated by Django 4.2.7 on 2025-10-14 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("abrir_mei", "Abrir MEI"),
                            ("regularizar_mei", "Regularizar MEI"),
                            ("declaracao_anual_mei", "Declaração Anual MEI"),
                            ("baixar_mei", "Baixar MEI"),
                            ("alteracao_mei", "Alteração MEI"),
                            ("inscricao_estadual", "Inscrição Estadual"),
                            ("parcelamento_mei", "Parcelamento MEI"),
                            ("certificado_mei", "Certificado MEI - CCMEI"),
                            ("desenquadramento_mei", "Desenquadramento MEI"),
                            ("reenquadramento_mei", "Reenquadramento MEI"),
                            ("nota_fiscal", "Nota Fiscal"),
                            ("buscar_mei_cpf", "Buscar MEI pelo CPF"),
                            (
                                "certidao_negativa_debitos",
                                "Certidão Negativa de Débitos",
                            ),
                            ("situacao_mei", "Situação MEI"),
                            ("alvara_funcionamento", "Alvará de Funcionamento"),
                            ("dividas_mei", "Dívidas MEI"),
                            ("licenca_maternidade", "Licença Maternidade"),
                            ("extrato_cnpj_mei", "Extrato CNPJ MEI"),
                            ("certidao_negativa_fgts", "Certidão Negativa de FGTS"),
                            (
                                "certidao_negativa_trabalhistas",
                                "Certidão Negativa de Débitos Trabalhistas",
                            ),
                            ("certidao_inss", "Certidão de INSS"),
                            ("aposentadoria_mei", "Aposentadoria MEI"),
                            ("certificado_digital", "Certificado Digital"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descricao", models.TextField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tempo_estimado",
                    models.CharField(help_text="Ex: 2-3 dias úteis", max_length=100),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "ordem",
                    models.IntegerField(default=0, help_text="Ordem de exibição"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Serviço",
                "verbose_name_plural": "Serviços",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="SolicitacaoServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em Andamento"),
                            ("aguardando_cliente", "Aguardando Cliente"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicos.servico",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Serviço",
                "verbose_name_plural": "Solicitações de Serviços",
                "ordering": ["-criado_em"],
            },
        ),
    ]
