# Generated by Django 5.2.3 on 2025-10-14 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitacaoMEI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=200)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("rg", models.CharField(max_length=15)),
                ("orgao_expedidor", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("telefone", models.CharField(max_length=15)),
                ("cnae_primario", models.CharField(max_length=20)),
                (
                    "cnaes_secundarios",
                    models.TextField(
                        blank=True, help_text="CNAEs separados por vírgula"
                    ),
                ),
                (
                    "forma_atuacao",
                    models.CharField(
                        choices=[
                            ("fixo", "Estabelecimento Fixo"),
                            ("internet", "Internet"),
                            ("televenda", "Televenda"),
                            ("porta_porta", "Porta a Porta"),
                            ("correio", "Correio"),
                            ("fixo_fora", "Em local fixo fora da loja"),
                            ("maquinas", "Máquinas automáticas"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "capital_inicial",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("cep", models.CharField(max_length=9)),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=2)),
                ("rua", models.CharField(max_length=200)),
                ("numero", models.CharField(max_length=10)),
                ("bairro", models.CharField(max_length=100)),
                ("complemento", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("processando", "Em Processamento"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Abertura MEI",
                "verbose_name_plural": "Solicitações de Abertura MEI",
                "ordering": ["-criado_em"],
            },
        ),
    ]
