# Generated by Django 5.2.3 on 2025-10-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0002_solicitacaomei"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitacaomei",
            name="cnaes_secundarios",
            field=models.TextField(blank=True, help_text="CNAE secundário opcional"),
        ),
    ]
