# Generated by Django 4.2.7 on 2025-10-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0003_alter_solicitacaomei_cnaes_secundarios"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaomei",
            name="estado_expedidor",
            field=models.CharField(default="", max_length=2),
        ),
    ]
