# Generated by Django 4.2.7 on 2025-10-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0004_solicitacaomei_estado_expedidor"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaomei",
            name="valor_servico",
            field=models.DecimalField(
                decimal_places=2,
                default=97.0,
                help_text="Valor cobrado pelo serviço de abertura MEI",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="solicitacaomei",
            name="venda_criada",
            field=models.BooleanField(
                default=False,
                help_text="Indica se a venda foi criada automaticamente no painel financeiro",
            ),
        ),
    ]
