# Generated by Django 4.2.7 on 2025-10-22 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("servicos", "0005_solicitacaomei_valor_servico_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitacaoBaixaMEI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cnpj_mei",
                    models.CharField(
                        help_text="Formato: 00.000.000/0001-00",
                        max_length=18,
                        verbose_name="CNPJ do MEI",
                    ),
                ),
                (
                    "nome_fantasia",
                    models.CharField(
                        help_text="Razão social ou nome fantasia do MEI",
                        max_length=200,
                        verbose_name="Nome Fantasia",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(
                        max_length=200, verbose_name="Nome Completo do Titular"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        help_text="Formato: 000.000.000-00",
                        max_length=14,
                        verbose_name="CPF do Titular",
                    ),
                ),
                ("rg", models.CharField(max_length=15, verbose_name="RG")),
                (
                    "orgao_emissor",
                    models.CharField(
                        help_text="Ex: SSP, DETRAN, PC",
                        max_length=10,
                        verbose_name="Órgão Emissor",
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="Data de Nascimento"),
                ),
                (
                    "nome_mae",
                    models.CharField(
                        max_length=200, verbose_name="Nome Completo da Mãe"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "telefone",
                    models.CharField(
                        help_text="Formato: (00) 00000-0000",
                        max_length=15,
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "cep",
                    models.CharField(
                        help_text="Formato: 00000-000", max_length=9, verbose_name="CEP"
                    ),
                ),
                (
                    "rua",
                    models.CharField(max_length=200, verbose_name="Rua/Logradouro"),
                ),
                ("numero", models.CharField(max_length=10, verbose_name="Número")),
                (
                    "complemento",
                    models.CharField(
                        blank=True,
                        help_text="Apartamento, sala, bloco, etc. (opcional)",
                        max_length=100,
                        verbose_name="Complemento",
                    ),
                ),
                ("bairro", models.CharField(max_length=100, verbose_name="Bairro")),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("processando", "Em Processamento"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        help_text="Informações adicionais sobre a solicitação",
                        verbose_name="Observações",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Solicitação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário Solicitante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Baixa MEI",
                "verbose_name_plural": "Solicitações de Baixa MEI",
                "ordering": ["-criado_em"],
            },
        ),
    ]
