# Generated by Django 4.2.7 on 2025-10-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descricao", models.TextField()),
                (
                    "beneficios",
                    models.JSONField(default=list, help_text="Lista de benefícios"),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "destaque",
                    models.BooleanField(default=False, help_text="Plano em destaque"),
                ),
                (
                    "ordem",
                    models.IntegerField(default=0, help_text="Ordem de exibição"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Plano",
                "verbose_name_plural": "Planos",
                "ordering": ["ordem", "preco"],
            },
        ),
    ]
